#!/usr/bin/env python3
"""The static assertions on the DEPLOY root's ``uv.lock`` -- the one the Apps build installs from.

Run as the last two steps of ``make app-lock``, and again by ``scripts/deploy-app.sh`` before it
uploads anything.

WHICH LOCKFILE. ``packages/shellbox-app/src/uv.lock``, generated by ``make app-lock`` from
``packages/shellbox-app/src/pyproject.toml``. That is the deploy root's manifest, and it is NOT
the workspace lockfile at the repository root. Both are gitignored and the reasons differ: the
workspace lockfile is a developer artifact, and this one is a DEPLOY-TIME artifact regenerated by
``make app-lock`` on every deploy.

WHY THE MIRROR REWRITE EXISTS, since these checks are what make it safe:

* This workstation resolves through an internal PyPI mirror. A user-level ``uv.toml`` names it as
  the default index, so a lock generated here records that host in every artifact URL and in the
  registry index URL. MEASURED 2026-08-04: all 187 URLs in a freshly generated deploy lock named
  the mirror and none named a public host.
* The Apps BUILD ENVIRONMENT cannot reach that host. The donor project
  ``databricks-code-search`` measured a wheel download timing out at deploy. So the rewrite is
  required, not defensive.
* The mirror preserves PyPI's URL layout 1:1 -- ``/simple/`` for the index and
  ``/packages/<hash-path>/<file>`` for artifacts -- so a HOST rewrite is exact and touches
  nothing else.
* The lock pins a per-artifact sha256 and the Apps build's ``uv sync --locked`` verifies it. A
  wrong rewrite therefore fails loudly at install rather than shipping a wrong artifact. That is
  the property that makes a textual host substitution an acceptable thing to do to a lockfile.
* It is a no-op on a workstation already resolving public PyPI.

WHY THIS IS A SECOND SCRIPT AND NOT A FLAG ON ``scripts/check_lockfile.py``. That script asserts
on the WORKSPACE lockfile in CI, and it asserts something different in two ways that do not
reconcile behind a flag:

1. It allows exactly one host, ``files.pythonhosted.org``, for every URL it finds. This file has
   to cover the ``registry`` index URL too, where ``pypi.org`` is the correct answer and
   ``files.pythonhosted.org`` would be wrong. Widening its allowlist would let a workspace
   lockfile name ``pypi.org`` in an artifact URL and still pass.
2. Its ``MIN_URL_COUNT`` floor is measured against the workspace's 64 packages. This lock has 36.

There is also a difference in WHEN each may run. ``check_lockfile.py`` documents that it is
CI-only, because on a mirror-configured laptop the workspace lock legitimately names the mirror
and its host assertion fails there by design. This script has no such restriction, and the
difference is the rewrite: by the time this runs, the file has been rewritten to public hosts
whatever index produced it. That is why ``make app-lock`` can run it on the owner's own laptop.

NOTE FOR THE PLAN RECORD. An earlier revision of the App-packaging plan carried a criterion
requiring the sha256 set to be byte-identical to the pre-rewrite lockfile. A later revision
dropped it because nothing in the repo was rewriting a lockfile. Something is now, so that
property is live again for this one file, and ``--assert-hashes-unchanged`` is where it is
checked. It is a criterion about the rewrite and about no other step.

CRITICAL: every mode asserts its input EXISTS, then asserts it FOUND what it is about to inspect,
and only then inspects it. That ordering is not padding. The obvious form of the host check --
``grep`` for the mirror, fail if it matched -- PASSES on a missing file and on an empty one,
because ``grep`` exits 2 on a missing file and 1 on no match, and the fail branch is never taken.
``scripts/check_lockfile.py`` and ``scripts/check_bundle_statics.py`` carry the same warning for
the same reason, and this repo has found that defect more than once.

The host rules are ALLOWLISTS and the comparisons are EXACT. A blocklist of internal names has to
name every mirror anyone might configure, and the one it does not name is the one that leaks. An
exact comparison matters because ``files.pythonhosted.org.example`` contains the allowed host and
is a different server.
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from collections import Counter
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

# The only host an ARTIFACT url may name -- an sdist or a wheel.
ARTIFACT_HOST = "files.pythonhosted.org"

# The only host a REGISTRY index url may name. A different host from the one above, and that
# distinction is the reason this file exists rather than a flag on scripts/check_lockfile.py.
INDEX_HOST = "pypi.org"

# The keys that hold a url, and what kind each one is.
#
# NOTE the residual, stated rather than left to be discovered: a lockfile format that grew a THIRD
# url-bearing key under a name neither of these matches would escape the host check silently. The
# floor below does not cover it either, because it counts artifact urls only. Two keys is what uv
# 0.10.9 writes, measured 2026-08-04 on the deploy lock; re-read this pair when the lockfile
# `version`/`revision` header changes.
ARTIFACT_KEY = "url"
INDEX_KEY = "registry"

# The non-vacuity floor: at least this many artifact urls, so a truncated or near-empty lock
# cannot pass by holding nothing to inspect.
#
# MEASURED, not guessed. On 2026-08-04, `make app-lock` on uv 0.10.9 produced a lock holding
# **187** artifact urls across 36 packages. The floor is 187 minus a margin of 67.
#
# The margin is sized to exceed the three largest per-package wheel sets combined -- cryptography
# 27, pydantic-core 20 and charset-normalizer 15, so 62 -- because dropping a dependency must not
# redden an untouched pull request. It is still far above what a broken generate step produces,
# which is zero.
#
# Re-measure and raise this when the dependency set changes materially. Record the new count, the
# date and the command, as above.
MIN_URL_COUNT = 120

# The hash key uv writes beside every artifact url, and the prefix it uses.
HASH_KEY = "hash"


def _fail(message: str) -> int:
    """Print the failure and return the failing exit status."""
    print(f"ERROR: {message}", file=sys.stderr)
    return 1


def _load(path: Path) -> dict[str, Any] | int:
    """The parsed lockfile, or a failing exit status with the reason already printed."""
    if not path.is_file():
        return _fail(
            f"{path} does not exist, so there is nothing to check. Run `make app-lock`, which "
            "generates it, rewrites the mirror hosts and then runs this script."
        )
    raw = path.read_bytes()
    if not raw:
        return _fail(f"{path} is empty.")
    try:
        return tomllib.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, tomllib.TOMLDecodeError) as error:
        # A truncated lockfile usually stops being valid TOML, so this is a check and not merely
        # input validation.
        return _fail(f"{path} is not valid TOML, so it is not a lockfile: {error}")


def _collect(node: Any, trail: str = "") -> list[tuple[str, str, str]]:
    """Every url-bearing string in the document, as ``(kind, key path, url)``.

    ``kind`` is ``ARTIFACT_KEY`` or ``INDEX_KEY``. The walk is recursive rather than reading
    ``package[].sdist.url`` and ``package[].wheels[].url`` by name: those are where uv writes
    today, and a check that names them stops covering a format that grows a third place.
    """
    found: list[tuple[str, str, str]] = []
    if isinstance(node, dict):
        for key, value in node.items():
            here = f"{trail}.{key}" if trail else key
            if key in (ARTIFACT_KEY, INDEX_KEY) and isinstance(value, str):
                found.append((key, here, value))
            else:
                found.extend(_collect(value, here))
    elif isinstance(node, list):
        for index, item in enumerate(node):
            found.extend(_collect(item, f"{trail}[{index}]"))
    return found


def _hashes(document: dict[str, Any]) -> Counter[str]:
    """Every ``hash`` value in the document, counted.

    A Counter and not a set, deliberately. Two artifacts legitimately share no hash, so a
    duplicate appearing or disappearing is a real change to what ships, and a set comparison
    would hide it.
    """
    found: Counter[str] = Counter()

    def walk(node: Any) -> None:
        if isinstance(node, dict):
            for key, value in node.items():
                if key == HASH_KEY and isinstance(value, str):
                    found[value] += 1
                else:
                    walk(value)
        elif isinstance(node, list):
            for item in node:
                walk(item)

    walk(document)
    return found


def assert_hosts(path: Path) -> int:
    """Assert the rewrite landed: no mirror anywhere, and every host is the expected public one."""
    document = _load(path)
    if isinstance(document, int):
        return document

    urls = _collect(document)
    if not urls:
        return _fail(
            f"{path} holds no urls at all. Either the generate step produced nothing usable, or "
            f"the lockfile format moved and this check no longer knows where to look "
            f"(it reads the {ARTIFACT_KEY!r} and {INDEX_KEY!r} keys)."
        )

    artifacts = [(where, url) for kind, where, url in urls if kind == ARTIFACT_KEY]
    indexes = [(where, url) for kind, where, url in urls if kind == INDEX_KEY]

    # Both kinds must be PRESENT. A lock holding only index urls, or only artifact urls, is one
    # this check would half-inspect while reporting success on the other half.
    if not artifacts:
        return _fail(f"{path} holds no {ARTIFACT_KEY!r} entries, so no artifact host was checked.")
    if not indexes:
        return _fail(f"{path} holds no {INDEX_KEY!r} entries, so no index host was checked.")

    offenders: list[tuple[str, str, str]] = []
    for where, url in artifacts:
        host = urlsplit(url).hostname or ""
        if host != ARTIFACT_HOST:
            offenders.append((where, host or "(no host)", url))
    for where, url in indexes:
        host = urlsplit(url).hostname or ""
        if host != INDEX_HOST:
            offenders.append((where, host or "(no host)", url))

    if offenders:
        hosts = sorted({host for _, host, _ in offenders})
        for where, host, url in offenders[:10]:
            print(f"  {where}: host {host!r} in {url}", file=sys.stderr)
        if len(offenders) > 10:
            print(f"  ... and {len(offenders) - 10} more", file=sys.stderr)
        return _fail(
            f"{len(offenders)} of {len(urls)} urls in {path} name an unexpected host: "
            f"{', '.join(hosts)}. Expected {ARTIFACT_HOST} for an artifact and {INDEX_HOST} for "
            f"the index. This lock still points at the index that resolved it, and the Apps "
            f"build environment cannot reach an internal mirror. `make app-lock` performs the "
            f"rewrite; a lock generated by hand has not had it."
        )

    if len(artifacts) < MIN_URL_COUNT:
        return _fail(
            f"{path} holds {len(artifacts)} artifact urls, fewer than the floor of "
            f"{MIN_URL_COUNT}. The generate step produced a truncated or near-empty lock. If the "
            f"dependency set really did shrink this far, re-measure and update MIN_URL_COUNT in "
            f"{Path(__file__).name} with the new number, the date and the command."
        )

    print(
        f"OK: {len(artifacts)} artifact urls on {ARTIFACT_HOST} and {len(indexes)} index urls on "
        f"{INDEX_HOST} in {path}; at or above the floor of {MIN_URL_COUNT}."
    )
    return 0


def assert_hashes_unchanged(path: Path, baseline: Path) -> int:
    """Assert the rewrite changed no hash, so it changed no artifact.

    ``baseline`` is the pre-rewrite file. ``make app-lock`` uses the ``.bak`` copy ``sed -i.bak``
    writes, so the baseline is the exact bytes the rewrite read and nothing regenerates it.
    """
    after = _load(path)
    if isinstance(after, int):
        return after
    before = _load(baseline)
    if isinstance(before, int):
        return before

    after_hashes = _hashes(after)
    before_hashes = _hashes(before)

    # The witness. Without it, two files holding no hashes at all compare equal and this reports
    # success on a rewrite of nothing.
    if not before_hashes:
        return _fail(
            f"{baseline} holds no {HASH_KEY!r} values, so there is nothing to compare. Either it "
            f"is not the pre-rewrite lockfile, or uv stopped pinning per-artifact hashes -- in "
            f"which case `uv sync --locked` no longer verifies what the rewrite produced, and "
            f"that is the assumption this whole step rests on."
        )

    if after_hashes != before_hashes:
        gained = after_hashes - before_hashes
        lost = before_hashes - after_hashes
        for value, count in sorted(lost.items())[:5]:
            print(f"  only before the rewrite (x{count}): {value}", file=sys.stderr)
        for value, count in sorted(gained.items())[:5]:
            print(f"  only after the rewrite  (x{count}): {value}", file=sys.stderr)
        return _fail(
            f"the rewrite changed the set of pinned hashes in {path}: {len(lost)} lost, "
            f"{len(gained)} gained. A HOST rewrite cannot do that -- it edits url hosts and "
            f"nothing else -- so the rewrite matched more than it was meant to, or the lock was "
            f"regenerated between the baseline and now. Do not deploy this file."
        )

    print(
        f"OK: the rewrite left all {sum(before_hashes.values())} pinned hashes "
        f"({len(before_hashes)} distinct) unchanged, so it changed no artifact."
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__ and __doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--assert-hosts",
        action="store_true",
        help="fail unless every artifact host is the public files host and every index host is "
        "the public index, and there are enough artifact urls",
    )
    mode.add_argument(
        "--assert-hashes-unchanged",
        action="store_true",
        help="fail unless the multiset of pinned hashes matches --baseline exactly",
    )
    parser.add_argument("path", type=Path, help="the deploy root's uv.lock")
    parser.add_argument(
        "--baseline",
        type=Path,
        help="the pre-rewrite lockfile; required with --assert-hashes-unchanged",
    )
    args = parser.parse_args(argv)

    if args.assert_hashes_unchanged:
        if args.baseline is None:
            parser.error("--assert-hashes-unchanged requires --baseline")
        return assert_hashes_unchanged(args.path, args.baseline)
    return assert_hosts(args.path)


if __name__ == "__main__":
    sys.exit(main())
